name = "redirect"
main = "build/worker/shim.mjs"
compatibility_date = "2023-01-31"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
workers_dev = false

routes = [
  "${ROUTE}"
]

[build]
command = "cargo install -q worker-build && worker-build --release"

[vars]
TARGET_BASE_URL = "${TARGET_BASE_URL}"
TARGET_FULL_URL = "${TARGET_FULL_URL}"
RESPONSE_CODE = "${RESPONSE_CODE}"
